/**
 * Curated MCU reference data.
 * The free APIs (TMDB/OMDb/TVmaze/Watchmode/Marvel) give ratings, cast, posters
 * and streaming links — but none of them know "in-universe chronological order"
 * or "which phase/saga a film belongs to". That editorial layer lives here.
 */

// ---- Sagas & Phases -------------------------------------------------------
window.MI_PHASES = [
  { id: "phase1", saga: "Infinity Saga", label: "Phase One", years: "2008–2012" },
  { id: "phase2", saga: "Infinity Saga", label: "Phase Two", years: "2013–2015" },
  { id: "phase3", saga: "Infinity Saga", label: "Phase Three", years: "2016–2019" },
  { id: "phase4", saga: "Multiverse Saga", label: "Phase Four", years: "2021–2022" },
  { id: "phase5", saga: "Multiverse Saga", label: "Phase Five", years: "2023–2025" },
  { id: "phase6", saga: "Multiverse Saga", label: "Phase Six", years: "2026–2027" },
  { id: "xmen", saga: "Mutant Saga / Fox-Marvel", label: "X-Men Saga", years: "2000–2024" },
  { id: "series", saga: "Disney+ Television", label: "Web Series & Specials", years: "2021–Present" }
];

// ---- Release-order roadmap (the "todo list" of the MCU & Marvel Universes) -
// status: "released" | "upcoming"
// type: "movie" | "series" | "xmen" | "special"
window.MI_ROADMAP = [
  // --- Phase 1 ---
  { title: "Iron Man", year: 2008, phase: "phase1", type: "movie", status: "released", tmdbQuery: "Iron Man", poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg" },
  { title: "The Incredible Hulk", year: 2008, phase: "phase1", type: "movie", status: "released", tmdbQuery: "The Incredible Hulk", poster: "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg" },
  { title: "Iron Man 2", year: 2010, phase: "phase1", type: "movie", status: "released", tmdbQuery: "Iron Man 2", poster: "https://image.tmdb.org/t/p/w500/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg" },
  { title: "Thor", year: 2011, phase: "phase1", type: "movie", status: "released", tmdbQuery: "Thor", poster: "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg" },
  { title: "Captain America: The First Avenger", year: 2011, phase: "phase1", type: "movie", status: "released", tmdbQuery: "Captain America The First Avenger", poster: "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg" },
  { title: "The Avengers", year: 2012, phase: "phase1", type: "movie", status: "released", tmdbQuery: "The Avengers", poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg" },

  // --- Phase 2 ---
  { title: "Iron Man 3", year: 2013, phase: "phase2", type: "movie", status: "released", tmdbQuery: "Iron Man 3", poster: "https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg" },
  { title: "Thor: The Dark World", year: 2013, phase: "phase2", type: "movie", status: "released", tmdbQuery: "Thor The Dark World", poster: "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg" },
  { title: "Captain America: The Winter Soldier", year: 2014, phase: "phase2", type: "movie", status: "released", tmdbQuery: "Captain America The Winter Soldier", poster: "https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg" },
  { title: "Guardians of the Galaxy", year: 2014, phase: "phase2", type: "movie", status: "released", tmdbQuery: "Guardians of the Galaxy", poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg" },
  { title: "Avengers: Age of Ultron", year: 2015, phase: "phase2", type: "movie", status: "released", tmdbQuery: "Avengers Age of Ultron", poster: "https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg" },
  { title: "Ant-Man", year: 2015, phase: "phase2", type: "movie", status: "released", tmdbQuery: "Ant-Man", poster: "https://image.tmdb.org/t/p/w500/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg" },

  // --- Phase 3 ---
  { title: "Captain America: Civil War", year: 2016, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Captain America Civil War", poster: "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg" },
  { title: "Doctor Strange", year: 2016, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Doctor Strange", poster: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg" },
  { title: "Guardians of the Galaxy Vol. 2", year: 2017, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Guardians of the Galaxy Vol 2", poster: "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg" },
  { title: "Spider-Man: Homecoming", year: 2017, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Spider-Man Homecoming", poster: "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg" },
  { title: "Thor: Ragnarok", year: 2017, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Thor Ragnarok", poster: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg" },
  { title: "Black Panther", year: 2018, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Black Panther", poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg" },
  { title: "Avengers: Infinity War", year: 2018, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Avengers Infinity War", poster: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg" },
  { title: "Ant-Man and the Wasp", year: 2018, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Ant-Man and the Wasp", poster: "https://image.tmdb.org/t/p/w500/cFQEO687n1K6umXbInzocxcnAQz.jpg" },
  { title: "Captain Marvel", year: 2019, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Captain Marvel", poster: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg" },
  { title: "Avengers: Endgame", year: 2019, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Avengers Endgame", poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg" },
  { title: "Spider-Man: Far From Home", year: 2019, phase: "phase3", type: "movie", status: "released", tmdbQuery: "Spider-Man Far From Home", poster: "https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg" },

  // --- Phase 4 Movies & Series ---
  { title: "WandaVision", year: 2021, phase: "phase4", type: "series", status: "released", tmdbQuery: "WandaVision", poster: "https://image.tmdb.org/t/p/w500/ijWWwINc8h71NQ8j1LTJMFSj5wr.jpg", runtimeMinutes: 350, priority: "must-watch" },
  { title: "The Falcon and the Winter Soldier", year: 2021, phase: "phase4", type: "series", status: "released", tmdbQuery: "The Falcon and the Winter Soldier", poster: "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg", runtimeMinutes: 300, priority: "recommended" },
  { title: "Loki (Season 1)", year: 2021, phase: "phase4", type: "series", status: "released", tmdbQuery: "Loki", poster: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg", runtimeMinutes: 280, priority: "must-watch" },
  { title: "Black Widow", year: 2021, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Black Widow", poster: "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg" },
  { title: "What If...? (Season 1)", year: 2021, phase: "phase4", type: "series", status: "released", tmdbQuery: "What If...?", poster: "https://image.tmdb.org/t/p/w500/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg", runtimeMinutes: 270, priority: "recommended" },
  { title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Shang-Chi", poster: "https://image.tmdb.org/t/p/w500/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg" },
  { title: "Eternals", year: 2021, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Eternals", poster: "https://image.tmdb.org/t/p/w500/lFByFSLV5WDJEv3KabbdAF959F2.jpg" },
  { title: "Hawkeye", year: 2021, phase: "phase4", type: "series", status: "released", tmdbQuery: "Hawkeye", poster: "https://image.tmdb.org/t/p/w500/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg", runtimeMinutes: 290, priority: "recommended" },
  { title: "Spider-Man: No Way Home", year: 2021, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Spider-Man No Way Home", poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg" },
  { title: "Moon Knight", year: 2022, phase: "phase4", type: "series", status: "released", tmdbQuery: "Moon Knight", poster: "https://image.tmdb.org/t/p/w500/x6FsYvt33846IQnDSFxla9j0RX8.jpg", runtimeMinutes: 280, priority: "recommended" },
  { title: "Doctor Strange in the Multiverse of Madness", year: 2022, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Doctor Strange Multiverse of Madness", poster: "https://image.tmdb.org/t/p/w500/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg" },
  { title: "Ms. Marvel", year: 2022, phase: "phase4", type: "series", status: "released", tmdbQuery: "Ms Marvel", poster: "https://image.tmdb.org/t/p/w500/3HWWh92kZbD7odwJX7nKmXNZsYo.jpg", runtimeMinutes: 270, priority: "recommended" },
  { title: "Thor: Love and Thunder", year: 2022, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Thor Love and Thunder", poster: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg" },
  { title: "She-Hulk: Attorney at Law", year: 2022, phase: "phase4", type: "series", status: "released", tmdbQuery: "She-Hulk Attorney at Law", poster: "https://image.tmdb.org/t/p/w500/5xz2orV8f0usyrfGNshcoXHmiaV.jpg", runtimeMinutes: 270, priority: "optional" },
  { title: "Werewolf by Night", year: 2022, phase: "phase4", type: "special", status: "released", tmdbQuery: "Werewolf by Night", poster: "https://image.tmdb.org/t/p/w500/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg", runtimeMinutes: 52, priority: "recommended" },
  { title: "The Guardians of the Galaxy Holiday Special", year: 2022, phase: "phase4", type: "special", status: "released", tmdbQuery: "Guardians Holiday Special", poster: "https://image.tmdb.org/t/p/w500/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg", runtimeMinutes: 44, priority: "optional" },
  { title: "Black Panther: Wakanda Forever", year: 2022, phase: "phase4", type: "movie", status: "released", tmdbQuery: "Wakanda Forever", poster: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg" },

  // --- Phase 5 Movies & Series ---
  { title: "Ant-Man and the Wasp: Quantumania", year: 2023, phase: "phase5", type: "movie", status: "released", tmdbQuery: "Quantumania", poster: "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg" },
  { title: "Guardians of the Galaxy Vol. 3", year: 2023, phase: "phase5", type: "movie", status: "released", tmdbQuery: "Guardians of the Galaxy Vol 3", poster: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg" },
  { title: "Secret Invasion", year: 2023, phase: "phase5", type: "series", status: "released", tmdbQuery: "Secret Invasion", poster: "https://image.tmdb.org/t/p/w500/3rINdUPSy9AklJg74jWHOyUXuZd.jpg", runtimeMinutes: 260, priority: "optional" },
  { title: "Loki (Season 2)", year: 2023, phase: "phase5", type: "series", status: "released", tmdbQuery: "Loki", poster: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg", runtimeMinutes: 290, priority: "must-watch" },
  { title: "The Marvels", year: 2023, phase: "phase5", type: "movie", status: "released", tmdbQuery: "The Marvels", poster: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg" },
  { title: "What If...? (Season 2)", year: 2023, phase: "phase5", type: "series", status: "released", tmdbQuery: "What If...?", poster: "https://image.tmdb.org/t/p/w500/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg", runtimeMinutes: 270, priority: "recommended" },
  { title: "Echo", year: 2024, phase: "phase5", type: "series", status: "released", tmdbQuery: "Echo", poster: "https://image.tmdb.org/t/p/w500/vFyJH630cF68LohVYjQW49074Sy.jpg", runtimeMinutes: 210, priority: "recommended" },
  { title: "X-Men '97", year: 2024, phase: "phase5", type: "series", status: "released", tmdbQuery: "X-Men 97", poster: "https://image.tmdb.org/t/p/w500/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg", runtimeMinutes: 320, priority: "must-watch" },
  { title: "Deadpool & Wolverine", year: 2024, phase: "phase5", type: "movie", status: "released", tmdbQuery: "Deadpool and Wolverine", poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg" },
  { title: "Agatha All Along", year: 2024, phase: "phase5", type: "series", status: "released", tmdbQuery: "Agatha All Along", poster: "https://image.tmdb.org/t/p/w500/mGsxKwXUjojitRv2E9qMTbxbBRd.jpg", runtimeMinutes: 340, priority: "must-watch" },
  { title: "Captain America: Brave New World", year: 2025, phase: "phase5", type: "movie", status: "released", tmdbQuery: "Captain America Brave New World", poster: "https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg" },
  { title: "Daredevil: Born Again", year: 2025, phase: "phase5", type: "series", status: "released", tmdbQuery: "Daredevil Born Again", poster: "https://image.tmdb.org/t/p/w500/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg", runtimeMinutes: 450, priority: "must-watch" },
  { title: "Thunderbolts*", year: 2025, phase: "phase5", type: "movie", status: "released", tmdbQuery: "Thunderbolts", poster: "https://image.tmdb.org/t/p/w500/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg" },
  { title: "Ironheart", year: 2025, phase: "phase5", type: "series", status: "released", tmdbQuery: "Ironheart", poster: "https://image.tmdb.org/t/p/w500/dOh6MJpdlQhYpLBhzhNQeYGKTZ5.jpg", runtimeMinutes: 280, priority: "recommended" },
  { title: "The Fantastic Four: First Steps", year: 2025, phase: "phase5", type: "movie", status: "released", tmdbQuery: "Fantastic Four First Steps", poster: "https://image.tmdb.org/t/p/w500/nf5qaSEvyYSNeFH0YhSs5EsBLX9.jpg" },
  { title: "Eyes of Wakanda", year: 2025, phase: "phase5", type: "series", status: "released", tmdbQuery: "Eyes of Wakanda", poster: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg", runtimeMinutes: 180, priority: "recommended" },
  { title: "Marvel Zombies", year: 2025, phase: "phase5", type: "series", status: "released", tmdbQuery: "Marvel Zombies", poster: "https://image.tmdb.org/t/p/w500/mwKj9ERGFXsWot0nXgQ5yMQf9I7.jpg", runtimeMinutes: 180, priority: "recommended" },

  // --- Phase 6 ---
  { title: "Spider-Man 4 (MCU)", year: 2026, releaseDate: "2026-07-24", phase: "phase6", type: "movie", status: "upcoming", tmdbQuery: null, poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", priority: "must-watch",
    synopsisFallback: "Peter Parker operates as a street-level hero in New York with his past erased, facing new gang threats and multiverse ripples." },
  { title: "Avengers: Doomsday", year: 2026, releaseDate: "2026-12-18", phase: "phase6", type: "movie", status: "upcoming", tmdbQuery: "Avengers Doomsday", spotlight: true, poster: "https://image.tmdb.org/t/p/w500/jzPwsojjFStf5lR5Nm07w2hH56G.jpg",
    synopsisFallback: "The Multiverse Saga's centerpiece — Doctor Doom rises as the Avengers, the Fantastic Four, X-Men and variants from across the multiverse are forced onto one battlefield." },
  { title: "Avengers: Secret Wars", year: 2027, releaseDate: "2027-12-17", phase: "phase6", type: "movie", status: "upcoming", tmdbQuery: "Avengers Secret Wars", poster: "https://image.tmdb.org/t/p/w500/f0YBuh4hyiAheXhh4JnJWoKi9g5.jpg",
    synopsisFallback: "The saga-closing event pulling together threads from Loki, What If...?, and the multiverse arc built since Endgame." },
  { title: "Blade", year: 2027, releaseDate: "2027-11-05", phase: "phase6", type: "movie", status: "upcoming", tmdbQuery: "Blade", poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    synopsisFallback: "Eric Brooks hunts the bloodsucking vampire underworld in the dark supernatural corner of the MCU." },
  { title: "Armor Wars", year: 2027, releaseDate: "2027-05-07", phase: "phase6", type: "movie", status: "upcoming", tmdbQuery: null, poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    synopsisFallback: "James Rhodes protects Tony Stark's legacy when high-tech Stark armor blueprints fall into black-market and rogue military hands." },

  // --- X-Men Saga (Fox-Marvel & Mutant Multiverse) ---
  { title: "X-Men", year: 2000, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "X-Men", poster: "https://image.tmdb.org/t/p/w500/2OFwsFhAobczgJWnVdwd9oZAF2N.jpg", runtimeMinutes: 104, priority: "must-watch",
    synopsisFallback: "Two mutants, Wolverine and Rogue, enter Charles Xavier's school while Magneto plots against humanity." },
  { title: "X2: X-Men United", year: 2003, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "X2 X-Men United", poster: "https://image.tmdb.org/t/p/w500/bst4alFUXCxISwdRUKSMhhkrX1M.jpg", runtimeMinutes: 134, priority: "must-watch",
    synopsisFallback: "The X-Men band together with Magneto's Brotherhood to stop Colonel William Stryker from exterminating all mutants." },
  { title: "X-Men: The Last Stand", year: 2006, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "X-Men The Last Stand", poster: "https://image.tmdb.org/t/p/w500/a2xicU8DpKtRizOHjQLC1JyCSRS.jpg", runtimeMinutes: 104, priority: "recommended",
    synopsisFallback: "A mutant cure sparks civil war while Jean Grey reawakens as the dark Phoenix." },
  { title: "X-Men: First Class", year: 2011, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "X-Men First Class", poster: "https://image.tmdb.org/t/p/w500/hNEokmUke0dazoBhttFN0o3L7Xv.jpg", runtimeMinutes: 132, priority: "must-watch",
    synopsisFallback: "In 1962 during the Cuban Missile Crisis, young Charles Xavier and Erik Lehnsherr unite mutants for the first time." },
  { title: "The Wolverine", year: 2013, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "The Wolverine", poster: "https://image.tmdb.org/t/p/w500/t2wVAcoRlKvEIVSbiYDb8d0QqqS.jpg", runtimeMinutes: 126, priority: "recommended",
    synopsisFallback: "Logan travels to Japan to meet an old friend, but finds his healing factor compromised." },
  { title: "X-Men: Days of Future Past", year: 2014, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "X-Men Days of Future Past", poster: "https://image.tmdb.org/t/p/w500/tYfijzolzgoMOtegh1Y7j2Enorg.jpg", runtimeMinutes: 132, priority: "must-watch",
    synopsisFallback: "Wolverine is sent into the past to prevent the creation of Sentinels that hunt mutants to extinction." },
  { title: "Deadpool", year: 2016, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "Deadpool", poster: "https://image.tmdb.org/t/p/w500/3E53WEZJqP6aM84D8CckXx4pIHw.jpg", runtimeMinutes: 108, priority: "must-watch",
    synopsisFallback: "A wisecracking mercenary with accelerated healing hunts down the rogue scientist who disfigured him." },
  { title: "X-Men: Apocalypse", year: 2016, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "X-Men Apocalypse", poster: "https://image.tmdb.org/t/p/w500/ikA8UhYdTGpqbatFa93nIf6noSr.jpg", runtimeMinutes: 144, priority: "optional",
    synopsisFallback: "The first and most powerful mutant awakens to cleanse mankind with his four horsemen." },
  { title: "Logan", year: 2017, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "Logan", poster: "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg", runtimeMinutes: 137, priority: "must-watch",
    synopsisFallback: "In a bleak future, an aging Logan cares for Charles Xavier while defending a young mutant girl, Laura." },
  { title: "Deadpool 2", year: 2018, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "Deadpool 2", poster: "https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg", runtimeMinutes: 119, priority: "must-watch",
    synopsisFallback: "Deadpool forms X-Force to protect a young mutant from time-traveling soldier Cable." },
  { title: "Dark Phoenix", year: 2019, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "Dark Phoenix", poster: "https://image.tmdb.org/t/p/w500/cCTJPelKGLhALq3r51A9uMonxKj.jpg", runtimeMinutes: 114, priority: "optional",
    synopsisFallback: "Jean Grey absorbs a solar flare in space, transforming into the cosmic Phoenix." },
  { title: "The New Mutants", year: 2020, phase: "xmen", type: "xmen", status: "released", tmdbQuery: "The New Mutants", poster: "https://image.tmdb.org/t/p/w500/xiDGcXJTvu1lazFRYip6g1eLt9c.jpg", runtimeMinutes: 94, priority: "optional",
    synopsisFallback: "Five young mutants held in an isolated facility must confront their traumatic pasts and powers." },
  { title: "Marvel Studios' Mutants / X-Men", year: 2028, phase: "xmen", type: "xmen", status: "upcoming", tmdbQuery: null, poster: "https://image.tmdb.org/t/p/w500/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg", runtimeMinutes: 130, priority: "must-watch",
    synopsisFallback: "The official MCU integration of the X-Men following Secret Wars, reimagining mutantkind in the Sacred Timeline." }
];

// ---- In-universe chronological timeline (curated story beats) ------------
window.MI_TIMELINE = [
  { year: "1943", title: "Captain America: The First Avenger", blurb: "Steve Rogers becomes the first Super-Soldier and crashes Red Skull's Hydra flagship into the Arctic, ending WWII's shadow war and putting himself on ice for 70 years." },
  { year: "1962 (Mutant Timeline)", title: "X-Men: First Class", blurb: "Charles Xavier and Erik Lehnsherr unite mutant refugees during the Cuban Missile Crisis, birthing the X-Men and Magneto's Brotherhood." },
  { year: "1973 (Fracture Point)", title: "X-Men: Days of Future Past", blurb: "Time-travel intervention stops Trask Industries' Sentinels, splintering the mutant timeline and creating an alternate path for mutantkind." },
  { year: "1995", title: "Captain Marvel", blurb: "Carol Danvers uncovers her Kree conditioning, reclaims her human memories, and helps the Skrulls find a new home — years before Tony Stark wears armor." },
  { year: "2000 (Earth-10005)", title: "X-Men", blurb: "Wolverine joins Professor X's team at Xavier's School to halt Magneto's mutation machine at Liberty Island." },
  { year: "2008", title: "Iron Man", blurb: "Weapons manufacturer Tony Stark builds a suit of armor to escape captivity, then chooses to become Iron Man instead of selling more weapons." },
  { year: "2008 (present)", title: "The Incredible Hulk", blurb: "Bruce Banner, hunted for the Hulk within him, faces the Abomination in Harlem — and General Ross's obsession with weaponizing the Hulk formula." },
  { year: "2010", title: "Iron Man 2", blurb: "Stark battles palladium poisoning and Ivan Vanko while SHIELD quietly assembles the Avengers Initiative around him." },
  { year: "2011 (Asgard)", title: "Thor", blurb: "Thor is exiled to Earth for his recklessness, learns humility from Jane Foster and SHIELD, and stops Loki's attempt to destroy Jotunheim to win their father's throne." },
  { year: "2012", title: "The Avengers", blurb: "Loki invades New York with the Chitauri; Earth's Mightiest Heroes assemble for the first time to close the portal." },
  { year: "2013", title: "Iron Man 3", blurb: "Stark confronts PTSD after New York while unraveling the Mandarin conspiracy and the Extremis program." },
  { year: "2013 (Asgard)", title: "Thor: The Dark World", blurb: "The Aether resurfaces, the Dark Elves attack the Nine Realms, and Thor loses his brother Loki (or does he?) stopping Malekith." },
  { year: "2014", title: "Captain America: The Winter Soldier", blurb: "Cap discovers Hydra has grown inside SHIELD itself, and learns the Winter Soldier is his old friend Bucky Barnes." },
  { year: "2014 (Cosmos)", title: "Guardians of the Galaxy", blurb: "Peter Quill and a ragtag crew stop Ronan the Accuser from using an Infinity Stone to annihilate Xandar." },
  { year: "2014", title: "Guardians of the Galaxy Vol. 2", blurb: "Quill meets his father Ego — a Celestial with plans to consume the galaxy — and the Guardians choose found family over blood." },
  { year: "2015", title: "Avengers: Age of Ultron", blurb: "Stark's peacekeeping AI turns genocidal; the Avengers create Vision and lose Sokovia in the fight to stop him." },
  { year: "2015", title: "Ant-Man", blurb: "Scott Lang becomes the new Ant-Man to stop Hank Pym's former protégé from weaponizing shrinking tech." },
  { year: "2016", title: "Captain America: Civil War", blurb: "The Sokovia Accords split the Avengers over accountability, and Zemo exposes that Bucky killed Tony's parents." },
  { year: "2016", title: "Black Widow", blurb: "Natasha Romanoff confronts her Red Room past and frees the other Widows while a fugitive from the Accords." },
  { year: "2016 (Sanctum)", title: "Doctor Strange", blurb: "Surgeon Stephen Strange loses his hands, gains the mystic arts, and bargains with Dormammu to save Earth from Kaecilius." },
  { year: "2017", title: "Spider-Man: Homecoming", blurb: "Peter Parker balances high school with stopping Adrian Toomes' black-market alien-tech weapons ring." },
  { year: "2017", title: "Thor: Ragnarok", blurb: "Thor loses his hammer and his home, teams with Hulk and Valkyrie, and lets Asgard burn to stop Hela." },
  { year: "2017", title: "Black Panther", blurb: "T'Challa becomes king of Wakanda and must decide whether to open its doors to the world after Killmonger's challenge." },
  { year: "2018", title: "Avengers: Infinity War", blurb: "Thanos gathers all six Infinity Stones and snaps half of all life in the universe out of existence." },
  { year: "2018", title: "Ant-Man and the Wasp", blurb: "Scott, Hope and Hank race to rescue Janet van Dyne from the Quantum Realm — just as the Blip hits." },
  { year: "2023", title: "Avengers: Endgame", blurb: "The surviving Avengers use time travel to undo the Snap, and Tony Stark sacrifices himself to defeat Thanos for good." },
  { year: "Outside Time (TVA)", title: "Loki (Season 1 & 2)", blurb: "A 2012 Loki variant is apprehended by the TVA, unmasks He Who Remains at the End of Time, and weaves the multiverse branches into Yggdrasil." },
  { year: "2023 (Hex)", title: "WandaVision", blurb: "Grief-stricken Wanda creates an idyllic sitcom reality in Westview, awakening as the prophetic Scarlet Witch before freeing the town." },
  { year: "2024", title: "The Falcon and the Winter Soldier", blurb: "Sam Wilson wrestles with the legacy of the shield, takes flight as the new Captain America, and reconciles Bucky's past." },
  { year: "2024", title: "Spider-Man: Far From Home", blurb: "Peter grieves Tony Stark while Mysterio frames him for chaos across Europe, ending with his identity exposed." },
  { year: "2024", title: "Moon Knight", blurb: "Mercenary Marc Spector and museum clerk Steven Grant discover their dissociative identity disorder is linked to Egyptian moon god Khonshu." },
  { year: "2024", title: "Hawkeye", blurb: "Clint Barton mentors Kate Bishop in New York during the holidays while confronting his Ronin enemies and Kingpin." },
  { year: "2025", title: "Shang-Chi and the Legend of the Ten Rings", blurb: "Shang-Chi confronts his father Wenwu and the Ten Rings' true, ancient cosmic purpose." },
  { year: "Timeless", title: "Eternals", blurb: "Ten immortal Eternals reveal their true purpose on Earth and split over Arishem's plan for humanity." },
  { year: "2024–25", title: "Doctor Strange in the Multiverse of Madness", blurb: "Strange and America Chavez traverse the multiverse to escape a corrupted Scarlet Witch hunting Chavez's power." },
  { year: "2025", title: "Spider-Man: No Way Home", blurb: "A broken spell tears open the multiverse, bringing villains and Spider-Men variants together; Peter chooses total anonymity to save reality." },
  { year: "2025", title: "Thor: Love and Thunder", blurb: "Thor teams with Jane Foster (now Mighty Thor) to stop Gorr the God Butcher from wiping out all gods." },
  { year: "2025", title: "Black Panther: Wakanda Forever", blurb: "Wakanda mourns T'Challa and faces Namor's underwater kingdom of Talokan; Shuri becomes the new Black Panther." },
  { year: "2026", title: "Ant-Man and the Wasp: Quantumania", blurb: "The Langs are pulled into the Quantum Realm and face Kang the Conqueror for the first time." },
  { year: "2026", title: "Guardians of the Galaxy Vol. 3", blurb: "The Guardians fight to save Rocket from the High Evolutionary, and go their separate ways." },
  { year: "2026", title: "The Marvels", blurb: "Carol Danvers, Kamala Khan and Monica Rambeau have their powers entangled and must work as one." },
  { year: "2026", title: "Agatha All Along", blurb: "Agatha Harkness navigates the perilous Witches' Road to reclaim her stripped powers alongside Billy Maximoff." },
  { year: "2026 (Parallel Void)", title: "Deadpool & Wolverine", blurb: "Wade Wilson recruits a Wolverine variant from a shattered world to stop Cassandra Nova in the Void, saving Earth-10005." },
  { year: "2027", title: "Daredevil: Born Again", blurb: "Matt Murdock and Mayor Wilson Fisk lock horns in New York City's brutal street war for justice and political power." },
  { year: "2028", title: "Captain America: Brave New World", blurb: "Sam Wilson, the new Captain America, uncovers a conspiracy tied to celestial Adamantium and an old enemy: Thaddeus Ross." },
  { year: "2028", title: "Thunderbolts*", blurb: "A team of morally grey operatives — the New Avengers in waiting — confront the Void, a manifestation of Bob's trauma." },
  { year: "2028 (Retro-Earth)", title: "The Fantastic Four: First Steps", blurb: "Earth's First Family faces Galactus and the Silver Surfer in a retro-futurist timeline, setting up their entry into the main MCU." },
  { year: "2029 (Dying World)", title: "Logan", blurb: "In an alternate 2029 where mutantkind is nearly wiped out, an aging Logan makes his final stand to usher Laura and children across the border." },
  { year: "2029 — the present crisis", title: "Avengers: Doomsday", blurb: "Variants collide as Victor von Doom steps out of the multiverse's shadows. The Fantastic Four, the X-Men, and every surviving Avenger converge for the fight that reshapes the Multiverse Saga.", spotlight: true },
  { year: "2029 — the finale", title: "Avengers: Secret Wars", blurb: "Incursions between universes threaten total collapse; heroes from every timeline the MCU has touched face the only fight big enough to close the saga." }
];

// ---- A small curated cast → character map (supplements TMDB credits) -----
window.MI_CHARACTERS = [
  { name: "Tony Stark / Iron Man", actor: "Robert Downey Jr.", aliases: ["Iron Man", "Anthony Stark"], powers: "Genius-level intellect, powered exo-suits, repulsor & unibeam weaponry, arc-reactor energy control.", firstAppearance: "Iron Man (2008)", affiliation: "Avengers" },
  { name: "Steve Rogers / Captain America", actor: "Chris Evans", aliases: ["Captain America", "The First Avenger", "Nomad"], powers: "Super-Soldier serum strength, speed & durability; vibranium shield mastery; peak tactical leadership.", firstAppearance: "Captain America: The First Avenger (2011)", affiliation: "Avengers" },
  { name: "Logan / Wolverine", actor: "Hugh Jackman", aliases: ["Wolverine", "Weapon X"], powers: "Mutant healing factor, enhanced animal senses, indestructible adamantium skeleton and retractable claws.", firstAppearance: "X-Men (2000)", affiliation: "X-Men / Deadpool & Wolverine" },
  { name: "Wade Wilson / Deadpool", actor: "Ryan Reynolds", aliases: ["Merc with a Mouth", "Deadpool"], powers: "Immortal regenerative factor, fourth-wall awareness, master marksman and swordsman.", firstAppearance: "X-Men Origins: Wolverine (2009)", affiliation: "X-Force / MCU Adjacent" },
  { name: "Charles Xavier / Professor X", actor: "Patrick Stewart", aliases: ["Professor X"], powers: "World's most powerful telepath, astral projection, Cerebro psychic amplification.", firstAppearance: "X-Men (2000)", affiliation: "X-Men / Illuminati" },
  { name: "Erik Lehnsherr / Magneto", actor: "Ian McKellen / Michael Fassbender", aliases: ["Magneto", "Master of Magnetism"], powers: "Total mastery over magnetic fields, metallic manipulation, force-field generation.", firstAppearance: "X-Men (2000)", affiliation: "Brotherhood of Mutants" },
  { name: "Matt Murdock / Daredevil", actor: "Charlie Cox", aliases: ["Daredevil", "The Man Without Fear"], powers: "Heightened superhuman senses, 360-degree radar sense, world-class acrobat and martial artist.", firstAppearance: "Daredevil (2015) / Spider-Man: No Way Home", affiliation: "Defenders / Avengers-adjacent" },
  { name: "Natasha Romanoff / Black Widow", actor: "Scarlett Johansson", aliases: ["Black Widow"], powers: "Red Room-trained master spy, expert martial artist, marksman, and interrogator.", firstAppearance: "Iron Man 2 (2010)", affiliation: "Avengers / S.H.I.E.L.D." },
  { name: "Thor Odinson", actor: "Chris Hemsworth", aliases: ["God of Thunder"], powers: "Asgardian physiology, weather/lightning manipulation, Mjolnir & Stormbreaker mastery.", firstAppearance: "Thor (2011)", affiliation: "Avengers / Asgard" },
  { name: "Bruce Banner / Hulk", actor: "Mark Ruffalo", aliases: ["Hulk", "Smart Hulk"], powers: "Gamma-fueled transformation into a near-invulnerable rage-powered giant; genius physicist.", firstAppearance: "The Avengers (2012)", affiliation: "Avengers" },
  { name: "Peter Parker / Spider-Man", actor: "Tom Holland", aliases: ["Spider-Man"], powers: "Spider-bite-derived strength, agility, wall-crawling, and precognitive 'spider-sense'.", firstAppearance: "Captain America: Civil War (2016)", affiliation: "Avengers" },
  { name: "T'Challa / Black Panther", actor: "Chadwick Boseman", aliases: ["Black Panther", "King of Wakanda"], powers: "Vibranium suit, Heart-Shaped Herb-enhanced strength & senses, master strategist.", firstAppearance: "Captain America: Civil War (2016)", affiliation: "Wakanda / Avengers" },
  { name: "Stephen Strange / Doctor Strange", actor: "Benedict Cumberbatch", aliases: ["Doctor Strange", "Sorcerer Supreme"], powers: "Mastery of the mystic arts, time manipulation via the Eye of Agamotto, astral projection.", firstAppearance: "Doctor Strange (2016)", affiliation: "Masters of the Mystic Arts" },
  { name: "Carol Danvers / Captain Marvel", actor: "Brie Larson", aliases: ["Captain Marvel", "Vers"], powers: "Photon-energy absorption & projection, flight, superhuman strength — one of the MCU's most powerful heroes.", firstAppearance: "Captain Marvel (2019)", affiliation: "Avengers / Kree (former)" },
  { name: "Wanda Maximoff / Scarlet Witch", actor: "Elizabeth Olsen", aliases: ["Scarlet Witch"], powers: "Chaos magic: reality alteration, telekinesis, telepathy; wields the Darkhold's forbidden knowledge.", firstAppearance: "Captain America: The Winter Soldier (2014, credits)", affiliation: "Avengers" },
  { name: "Loki Laufeyson", actor: "Tom Hiddleston", aliases: ["God of Stories", "God of Mischief"], powers: "Temporal weaving, illusion casting, shapeshifting, multiverse anchor holding all timelines.", firstAppearance: "Thor (2011)", affiliation: "TVA / Multiverse Core" },
  { name: "Victor von Doom", actor: "Robert Downey Jr.", aliases: ["Doctor Doom"], powers: "Sorcery and Latverian science fused into one of the multiverse's most dangerous minds; master of both magic and technology.", firstAppearance: "Avengers: Doomsday (2026)", affiliation: "Latveria" }
];

// ---- Curated Official Marvel Trailers & Footage (100% Verified Active YouTube IDs) ------------
window.MI_TRAILERS = [
  {
    id: "trailer-avengers-endgame",
    title: "Avengers: Endgame — Official Trailer",
    movieTitle: "Avengers: Endgame",
    year: "2019",
    phase: "Phase Three",
    category: "infinity-saga",
    categoryLabel: "Infinity Saga",
    youtubeId: "TcMBFSGVi1c",
    duration: "2:26",
    quality: "4K UHD",
    releaseDate: "2019",
    channel: "Marvel Studios",
    blurb: "'Whatever it takes.' The surviving Avengers assemble for one final desperate mission to undo Thanos's devastation.",
    featured: true
  },
  {
    id: "trailer-avengers-infinity-war",
    title: "Avengers: Infinity War — Official Trailer 1",
    movieTitle: "Avengers: Infinity War",
    year: "2018",
    phase: "Phase Three",
    category: "infinity-saga",
    categoryLabel: "Infinity Saga",
    youtubeId: "6ZfuNTqbHE8",
    duration: "2:25",
    quality: "4K UHD",
    releaseDate: "2018",
    channel: "Marvel Studios",
    blurb: "Ten years of the Marvel Cinematic Universe culminate as Earth's mightiest heroes face the mad Titan Thanos.",
    featured: true
  },
  {
    id: "trailer-thunderbolts",
    title: "Thunderbolts* — Official Teaser Trailer",
    movieTitle: "Thunderbolts*",
    year: "2025",
    phase: "Phase Five",
    category: "multiverse",
    categoryLabel: "Phase 5 & Multiverse",
    youtubeId: "v-94Snw-H4o",
    duration: "3:25",
    quality: "4K UHD",
    releaseDate: "2025",
    channel: "Marvel Studios",
    blurb: "Florence Pugh, Sebastian Stan, David Harbour and Wyatt Russell lead an irreverent squad of MCU anti-heroes trapped in a lethal government operation.",
    featured: true
  },
  {
    id: "trailer-spiderman-nwh",
    title: "Spider-Man: No Way Home — Official Teaser Trailer",
    movieTitle: "Spider-Man: No Way Home",
    year: "2021",
    phase: "Phase Four",
    category: "multiverse",
    categoryLabel: "Multiverse Saga",
    youtubeId: "JfVOs4VSpmA",
    duration: "3:04",
    quality: "4K UHD",
    releaseDate: "2021",
    channel: "Sony Pictures & Marvel Studios",
    blurb: "When Peter Parker's identity is exposed, a spell gone wrong unearths legendary villains and three generations of Spider-Men across dimensions.",
    featured: true
  },
  {
    id: "trailer-guardians-vol-3",
    title: "Guardians of the Galaxy Vol. 3 — Official Trailer",
    movieTitle: "Guardians of the Galaxy Vol. 3",
    year: "2023",
    phase: "Phase Five",
    category: "multiverse",
    categoryLabel: "Phase 5 & Multiverse",
    youtubeId: "u3V5KDHRQvk",
    duration: "2:20",
    quality: "4K UHD",
    releaseDate: "2023",
    channel: "Marvel Studios",
    blurb: "Our beloved band of misfits embark on a dangerous mission to save Rocket's life that could lead to the end of the Guardians as we know them.",
    featured: false
  },
  {
    id: "trailer-civil-war",
    title: "Captain America: Civil War — Official Trailer 1",
    movieTitle: "Captain America: Civil War",
    year: "2016",
    phase: "Phase Three",
    category: "infinity-saga",
    categoryLabel: "Infinity Saga",
    youtubeId: "dKrVegVI0Us",
    duration: "2:26",
    quality: "4K UHD",
    releaseDate: "2016",
    channel: "Marvel Studios",
    blurb: "Steve Rogers and Tony Stark clash over ideological divides and government oversight, tearing the Avengers apart.",
    featured: false
  },
  {
    id: "trailer-black-panther",
    title: "Black Panther — Official Trailer",
    movieTitle: "Black Panther",
    year: "2018",
    phase: "Phase Three",
    category: "infinity-saga",
    categoryLabel: "Infinity Saga",
    youtubeId: "xjDjIWPwcPU",
    duration: "2:18",
    quality: "4K UHD",
    releaseDate: "2018",
    channel: "Marvel Studios",
    blurb: "T'Challa returns home to the isolated, technologically advanced African nation of Wakanda to succeed to the throne as king.",
    featured: false
  },
  {
    id: "trailer-thor-ragnarok",
    title: "Thor: Ragnarok — Official Teaser Trailer",
    movieTitle: "Thor: Ragnarok",
    year: "2017",
    phase: "Phase Three",
    category: "infinity-saga",
    categoryLabel: "Infinity Saga",
    youtubeId: "ue80QwXMRHg",
    duration: "1:58",
    quality: "4K UHD",
    releaseDate: "2017",
    channel: "Marvel Studios",
    blurb: "Thor finds himself in a deadly gladiatorial contest against the Hulk before racing to save Asgard from the ruthless Hela.",
    featured: false
  },
  {
    id: "trailer-loki-s2",
    title: "Loki Season 2 — Official Trailer",
    movieTitle: "Loki",
    year: "2023",
    phase: "Disney+ Series",
    category: "series",
    categoryLabel: "Disney+ Series",
    youtubeId: "dug56u8NN7g",
    duration: "2:23",
    quality: "4K UHD",
    releaseDate: "2023",
    channel: "Marvel Studios",
    blurb: "Loki navigates time-slipping across past, present, and future at the TVA, journeying toward his glorious transformation into the God of Stories.",
    featured: false
  },
  {
    id: "trailer-agatha-all-along",
    title: "Agatha All Along — Official Trailer",
    movieTitle: "Agatha All Along",
    year: "2024",
    phase: "Disney+ Series",
    category: "series",
    categoryLabel: "Disney+ Series",
    youtubeId: "R9ptO8n5d78",
    duration: "2:15",
    quality: "4K UHD",
    releaseDate: "2024",
    channel: "Marvel Studios",
    blurb: "Kathryn Hahn leads a desperate coven of witches down the legendary and deadly Witches' Road to reclaim her arcane powers.",
    featured: false
  },
  {
    id: "trailer-xmen-97",
    title: "X-Men '97 — Official Trailer",
    movieTitle: "X-Men '97",
    year: "2024",
    phase: "Mutant Era",
    category: "series",
    categoryLabel: "Animation & Series",
    youtubeId: "pv3Ss8o9auU",
    duration: "1:48",
    quality: "HD",
    releaseDate: "2024",
    channel: "Marvel Animation",
    blurb: "The animated mutant icons return to confront a world that hates and fears them, continuing the legendary 1990s animated series storyline.",
    featured: false
  }
];

// ---- Curated Marvel India Merchandise (Amazon Affiliate) -----------------
window.MI_AFFILIATE_PRODUCTS = [
  {
    id: 1,
    title: "Marvel Avengers Legends Series Infinity Gauntlet Prop Replica",
    category: "Collectibles",
    tag: "Fan Favorite",
    price_label: "₹8,499",
    price_num: 8499,
    mrp: "₹11,999",
    discount_percent: "29% off",
    rating: 4.8,
    reviews_count: "2,480",
    image_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    amazon_url: "https://www.amazon.in/s?k=marvel+legends+infinity+gauntlet",
    blurb: "Articulated electronic fist with pulsating LED Infinity Stones, movie-inspired sound FX, and finger lock display mode."
  },
  {
    id: 2,
    title: "Hasbro Marvel Legends 6-Inch Deadpool & Wolverine Collectible Figure",
    category: "Action Figures",
    tag: "Bestseller",
    price_label: "₹2,799",
    price_num: 2799,
    mrp: "₹3,499",
    discount_percent: "20% off",
    rating: 4.9,
    reviews_count: "1,150",
    image_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    amazon_url: "https://www.amazon.in/s?k=marvel+legends+deadpool+wolverine",
    blurb: "Premium comic-accurate articulation with interchangeable hands, katana swords, and signature weapons from the hit film."
  },
  {
    id: 3,
    title: "Captain America 24-Inch 75th Anniversary Metal Shield Replica",
    category: "Cosplay & Replicas",
    tag: "Collector Edition",
    price_label: "₹6,999",
    price_num: 6999,
    mrp: "₹9,999",
    discount_percent: "30% off",
    rating: 4.7,
    reviews_count: "890",
    image_url: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=600&auto=format&fit=crop&q=80",
    amazon_url: "https://www.amazon.in/s?k=captain+america+shield+replica+metal",
    blurb: "Full-scale 1:1 replica featuring premium dual adjustable leather arm straps and high-gloss vibranium finish."
  },
  {
    id: 4,
    title: "Secret Wars (2015) Marvel Omnibus Hardcover by Jonathan Hickman",
    category: "Comics & Graphic Novels",
    tag: "Essential Reading",
    price_label: "₹3,250",
    price_num: 3250,
    mrp: "₹4,500",
    discount_percent: "28% off",
    rating: 4.9,
    reviews_count: "3,420",
    image_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    amazon_url: "https://www.amazon.in/s?k=secret+wars+omnibus+hickman",
    blurb: "The definitive multiverse incursion epic directly inspiring Avengers: Secret Wars & Doomsday. Oversized full-color omnibus."
  },
  {
    id: 5,
    title: "Loki TVA Golden TempPad Time Travel Clock Desk Prop",
    category: "Collectibles",
    tag: "Trending",
    price_label: "₹1,899",
    price_num: 1899,
    mrp: "₹2,499",
    discount_percent: "24% off",
    rating: 4.6,
    reviews_count: "640",
    image_url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    amazon_url: "https://www.amazon.in/s?k=loki+tva+temppad+prop",
    blurb: "Interactive desktop LED chronometer modeled after Miss Minutes and the Time Variance Authority time-door devices."
  },
  {
    id: 6,
    title: "Marvel Studios The Infinity Saga 4K Ultra HD Box Set (Phases 1-3)",
    category: "Movies & Blu-Ray",
    tag: "Ultimate Box Set",
    price_label: "₹14,999",
    price_num: 14999,
    mrp: "₹19,999",
    discount_percent: "25% off",
    rating: 4.9,
    reviews_count: "1,870",
    image_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80",
    amazon_url: "https://www.amazon.in/s?k=marvel+infinity+saga+4k+box+set",
    blurb: "All 23 groundbreaking Infinity Saga films remastered with Dolby Atmos, deleted scenes, gag reels, and exclusive lithographs."
  }
];

